[project]
name = "mangomusic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anika Achary", email = "anika.achary@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "librosa>=1.0.0",
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
]

[project.scripts]
mangomusic = "mangomusic:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "nbstripout>=0.9.1",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]

[tool.pyright]
typeCheckingMode = "strict"
venvPath = '.'
venv = '.venv'
